name: rjd-glimpse
title: glimpse
version: 'v2.0.0' 
summary:   Tool for low-coverage whole-genome imputation 
description: |
        "GLIMPSE2 is a set of tools for low-coverage whole genome sequencing imputation. GLIMPSE2 is based on the GLIMPSE model and designed for reference panels containing hundreads of thousands of reference samples, with a special focus on rare variants."
          *  The description above refers to the software: https://odelaneau.github.io/GLIMPSE/
          * I have packaged the software as a snap for **personal use** but I have made the snap available for free.
          * I   do not maintain the software itself. I only maintain the snap packaging. Please report software bugs to the maintainers.
          * Report snap-specific bugs to me.
          * I _DO_ use this snap. It _HAS PASSED ALL THE PROVIDED TESTS_ on my system. I __do not__ track the latest version.
          * Packaging 'style' : binary for linux machines.
          * License refers to the original software, not the snapcraft 'code'.
          * Run the following to rename the snap commands to GLIMPSE2_<command>
                ```sudo snap alias rjd-glimpse.chunk GLIMPSE2_chunk```
                ```sudo snap alias rjd-glimpse.concordance GLIMPSE2_concordance```
                ```sudo snap alias rjd-glimpse.ligate GLIMPSE2_ligate```
                ```sudo snap alias rjd-glimpse.phase GLIMPSE2_phase```
                ```sudo snap alias rjd-glimpse.split-reference GLIMPSE2_split_reference```
#          * More info:

contact: https://github.com/RJDan/glimpse_snap
website: https://github.com/RJDan/glimpse_snap
source-code : https://github.com/RJDan/glimpse_snap
icon:  Icon_230417.png

base: core22 # the base snap is the execution environment for this snap
grade: stable # stable, devel
confinement: strict # strict, devmode, classic
license:  MIT
architectures:
      - amd64

  
apps:
    glimpse-chunk:
        command: bin/chunk_static
        plugs:
          - home
          - removable-media
    glimpse-concordance:
        command: bin/concordance_static
        plugs:
          - home
          - removable-media
    glimpse-ligate:
        command: bin/ligate_static
        plugs:
          - home
          - removable-media
    glimpse-phase:
        command: bin/phase_static
        plugs:
          - home
          - removable-media
    glimpse-split-reference:
        command: bin/split_reference_static
        plugs:
          - home
          - removable-media

parts:
    glimpse:
        plugin: dump
        source: https://github.com/odelaneau/GLIMPSE/releases/download/v2.0.0/glimpse_v2.0.0-27-g0919952_20221207.tar.gz
        build-packages:
                - wget
                - tree
                - tar
        override-pull: |
                    wget https://github.com/odelaneau/GLIMPSE/releases/download/v2.0.0/GLIMPSE2_chunk_static
                    wget https://github.com/odelaneau/GLIMPSE/releases/download/v2.0.0/GLIMPSE2_concordance_static
                    wget https://github.com/odelaneau/GLIMPSE/releases/download/v2.0.0/GLIMPSE2_ligate_static
                    wget https://github.com/odelaneau/GLIMPSE/releases/download/v2.0.0/GLIMPSE2_phase_static
                    wget https://github.com/odelaneau/GLIMPSE/releases/download/v2.0.0/GLIMPSE2_split_reference_static 
                    craftctl default
        override-build: |
                    mv GLIMPSE2* $SNAPCRAFT_PART_INSTALL                    
                    chmod +x $SNAPCRAFT_PART_INSTALL/GLIMPSE2_chunk_static
                    chmod +x $SNAPCRAFT_PART_INSTALL/GLIMPSE2_concordance_static
                    chmod +x $SNAPCRAFT_PART_INSTALL/GLIMPSE2_ligate_static
                    chmod +x $SNAPCRAFT_PART_INSTALL/GLIMPSE2_phase_static
                    chmod +x $SNAPCRAFT_PART_INSTALL/GLIMPSE2_split_reference_static 
                    craftctl default
        organize:
                    GLIMPSE2_chunk_static: bin/chunk_static
                    GLIMPSE2_concordance_static: bin/concordance_static
                    GLIMPSE2_ligate_static: bin/ligate_static
                    GLIMPSE2_phase_static: bin/phase_static
                    GLIMPSE2_split_reference_static : bin/split_reference_static 
                    "glimpse_logo_400x171.png" : snap/Icon_230417.png
        stage:
            - bin
            #- test
            #- doc
        prime:
            - bin
            #- doc
            #- test

