name: rjd-impute
title: impute
version: '5v1.2.0'
summary:   Genotype imputation method 
description: |
        "IMPUTE 5 is a genotype imputation method that can scale to reference panels with millions of samples. It achieves fast, accurate, and memory-efficient imputation by selecting haplotypes using the Positional Burrows Wheeler Transform (PBWT)."
          *  The description above refers to the software: https://jmarchini.org/software/
          * I have packaged the software as a snap for **personal use** but I have made the snap available for free.
          * I   do not maintain the software itself. I only maintain the snap packaging. Please report software bugs to the maintainers.
          * Report snap-specific bugs to me.
          * I _DO_ use this snap. It _HAS PASSED ALL THE PROVIDED TESTS_ on my system. I __do not__ track the latest version.
          * Packaging 'style' : binary for linux machines.
          * License refers to the original software, not the snapcraft 'code'.
          * Run the following to rename the snap
                ```sudo snap alias rjd-impute.impute5 impute5```
                ```sudo snap alias rjd-impute.imp5Chunker imp5Chunker```
                ```sudo snap alias rjd-impute.xcftools xcftools```
#          * More info:

contact: https://github.com/RJDan/impute_snap
website: https://github.com/RJDan/impute_snap
source-code : https://github.com/RJDan/impute_snap
#icon: Rlogo.png

base: core22 # the base snap is the execution environment for this snap
grade: stable # stable, devel
confinement: strict # strict, devmode, classic
license:  MIT
architectures:
      - amd64

apps:
    imp5Chunker:
        command: bin/imp5Chunker
        plugs:
          - home
          - removable-media
    xcftools:
        command: bin/xcftools
        plugs:
          - home
          - removable-media
    impute5:
        command: bin/impute5
        plugs:
          - home
          - removable-media

parts:
    impute:
        plugin: dump
        source: .
        build-packages:
                - wget
                - tree
                - unzip
        override-pull: |
                    wget dl.dropboxusercontent.com/sh/mwnceyhir8yze2j/AABKBCgZsQqz8TlZGo7yXwx6a/impute5_v1.2.0.zip?dl=0
                    mv impute5_v1.2.0.zip?dl=0 impute5_v1.2.0.zip
                    unzip impute5_v1.2.0.zip
                    snapcraftctl pull
        override-build: |
                    mv impute5_v1.2.0/* $SNAPCRAFT_PART_INSTALL
                    chmod +x $SNAPCRAFT_PART_INSTALL/imp5Chunker_v1.2.0_static
                    chmod +x $SNAPCRAFT_PART_INSTALL/impute5_v1.2.0_static 
                    chmod +x $SNAPCRAFT_PART_INSTALL/xcftools_static
                    snapcraftctl build
        organize:
            imp5Chunker_v1.2.0_static : bin/imp5Chunker
            impute5_v1.2.0_static : bin/impute5
            xcftools_static : bin/xcftools
        stage:
            - bin
            - test
            - doc
        prime:
            - bin
            - doc
            - test

#            "Icon_230417.svg" : snap/Icon_230417.svg
#        build-packages:
#        stage-packages:
